[package]
name = "rust-grpc"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic = "0.11"
tokio = { version = "1", features = ["full"] }
prost = "0.12"
tokio-stream = "0.1"
futures-core = "0.3"


[build-dependencies]
tonic-build = "0.11"